[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI-Driven Creative Writing: Techniques and Strategies for Innovative Storytelling with Artificial Intelligence"
